export const modelCards = [
  {
    name: 'Persistencia',
    family: 'Baseline',
    summary: 'ŷ(t+h) = y(t). Baseline elemental sin entrenamiento ni hiperparámetros.',
    config: [{ param: 'Regla', value: 'nivel futuro = nivel actual' }],
    source: 'Cap. 4.4.1',
  },
  {
    name: 'ARIMA',
    family: 'Estadístico',
    summary: 'ARIMA(2,1,1) seleccionado en validación y aplicado con walk-forward.',
    config: [
      { param: 'Orden', value: 'ARIMA(2,1,1)' },
      { param: 'Validación', value: 'Walk-forward (solo ARIMA/ARIMAX)' },
    ],
    source: 'Cap. 4.4.2',
  },
  {
    name: 'ARIMAX',
    family: 'Estadístico',
    summary: 'Núcleo ARIMA(2,1,1) con precipitación antecedente causal (sin lluvia futura).',
    config: [
      { param: '1 h', value: 'ARIMAX_lluvia_multi' },
      { param: '2 h', value: 'ARIMAX_lluvia_1h' },
      { param: '3 h', value: 'ARIMAX_lluvia_1h' },
    ],
    source: 'Tabla 14, cap. 4.4.3',
  },
  {
    name: 'Random Forest',
    family: 'Machine Learning',
    summary: 'Variante RF_sqrt congelada para los tres horizontes.',
    config: [
      { param: 'n_estimators', value: '400' },
      { param: 'max_depth', value: '20' },
      { param: 'min_samples_leaf', value: '2' },
      { param: 'max_features', value: 'sqrt' },
    ],
    source: 'Tabla 15, cap. 4.5.1',
  },
  {
    name: 'XGBoost',
    family: 'Machine Learning',
    summary: 'Variante XGB_regularizado congelada para los tres horizontes.',
    config: [
      { param: 'n_estimators', value: '700' },
      { param: 'max_depth', value: '4' },
      { param: 'learning_rate', value: '0,03' },
      { param: 'min_child_weight', value: '3' },
      { param: 'subsample', value: '0,9' },
      { param: 'colsample_bytree', value: '0,8' },
      { param: 'reg_alpha', value: '0,1' },
      { param: 'reg_lambda', value: '5,0' },
      { param: 'gamma', value: '0,0' },
    ],
    source: 'Tabla 16, cap. 4.5.2',
  },
  {
    name: 'LSTM',
    family: 'Deep Learning',
    summary: 'Input(37,2) → LSTM(64) → Dropout(0,10) → LSTM(32) → Dense(32,ReLU) → Dense(1).',
    config: [
      { param: 'Entrada', value: '37 × 2' },
      { param: 'Optimizador', value: 'Adam, lr=0,001' },
      { param: 'Pérdida', value: 'MSE' },
      { param: 'batch_size', value: '128' },
      { param: 'Épocas 1/2/3 h', value: '37 / 31 / 40' },
      { param: 'Patience', value: '8' },
      { param: 'Shuffle', value: 'False' },
    ],
    source: 'Tabla 17, cap. 4.6.2',
  },
  {
    name: 'GRU',
    family: 'Deep Learning',
    summary: 'Input(37,2) → GRU(64) → Dropout(0,10) → GRU(32) → Dense(32,ReLU) → Dense(1).',
    config: [
      { param: 'Entrada', value: '37 × 2' },
      { param: 'Optimizador', value: 'Adam, lr=0,001' },
      { param: 'Pérdida', value: 'MSE' },
      { param: 'batch_size', value: '128' },
      { param: 'Épocas 1/2/3 h', value: '38 / 36 / 38' },
      { param: 'Patience', value: '8' },
      { param: 'Shuffle', value: 'False' },
    ],
    source: 'Tabla 18, cap. 4.6.3',
  },
] as const

export const environment = {
  seed: 42,
  rows: [
    { component: 'Python', version: '3.12.13' },
    { component: 'Sistema operativo', version: 'Linux 6.6.122+' },
    { component: 'NumPy', version: '2.0.2' },
    { component: 'pandas', version: '2.2.2' },
    { component: 'matplotlib', version: '3.10.0' },
    { component: 'scikit-learn', version: '1.6.1' },
    { component: 'statsmodels', version: '0.14.6' },
    { component: 'XGBoost', version: '3.3.0' },
    { component: 'TensorFlow', version: '2.20.0' },
    { component: 'PyArrow', version: '18.1.0' },
    { component: 'Keras', version: '3.13.2' },
  ],
  notes: [
    'Ejecución en Google Colab. Durante LSTM/GRU no se detectó GPU disponible.',
    'Configuraciones congeladas antes de observar métricas de TEST; sin tuning posterior.',
    'Walk-forward aplica específicamente a ARIMA y ARIMAX; RF/XGB/LSTM/GRU usan Train/Val/TEST cronológico.',
  ],
  source: 'Tabla 19, cap. 4.8',
}
